### ISSUE TITLE
I couldn't open document website.

### ISSUE THREAD

**Issue by RedheatWei** [wowdev/pywowlib#2]
I couldn't open http://model-changing.net.
I hope have documents tell me how to use this lib.

**Comment by skarnproject** [comment]
Model-Changing is currently being moved to another hosting option, sorry.
There are not documents yet as the lib is in development. What do you want to do with it?

**Comment by RedheatWei** [comment]
I'm trying read map file and draw a coordinate in 3D model. But I have no idea how to do this.
So I tried to read your code. And the issue is I didn't know how to use your lib and what's meaning for a function. So I want a document to read.

**Comment by skarnproject** [comment]
Sorry, documentation will be available later when the library is more finished.
