### ISSUE TITLE
Use of the tool.

### ISSUE THREAD

**Issue by pangolp** [wowdev/pywowlib#5]
Hey, first of all, thanks for sharing the tool. Clone the repository, create a virtual environment where you install all the dependencies, but the truth is that I don't understand how to really use it. I would love to make a video (which would be in Spanish) showing the use of it and giving some example to respect.

Any information to the respect would serve me.
Thank you.

**Comment by skarnproject** [comment]
It is still in the development process, so I have not yet written any docs for this. You can read files by using classes from the root of the library's dir for now.

**Comment by pangolp** [comment]
Okay, thanks for the information. I will wait patiently to spread this great tool. I tried to convert .wmo files, but I didn't really get around to it.
